### ISSUE TITLE
deploying CBRA with Docker

### ISSUE THREAD

**Issue by dreyks** [shageman/cbra_book_code#1]
When deploying a vanilla Rails app with Docker the usual way is to copy Gemfile and Gemfile.lock first, `bundle install` and only then copy the rest part of the app. This is done to leverage Docker cache and do not rebuild all the gems if the changes are only in your code.
```Dockerfile
COPY Gemfile* /tmp/
WORKDIR /tmp
RUN bundle install
```
However when using CBRA there's no(?) way I can do this: I have to copy all the `components/**/*.gemspec`s hierarchically, which Docker can't do

Any suggestions?

**Comment by shageman** [comment]
Hey dreyks,

Sorry for the late response. My notification settings were screwed up.

If this is still of interest to you, can you send me a script of the vanilla case you are describing? I take it you are using this on your local machine during development, correct?

Thanks,
Stephan

**Comment by dreyks** [comment]
Hi!

This is used when building docker images for production. In development I use docker-compose and dedicated bundler volume.

The vanilla app case is described in the issue: build-progress copies Gemfile and Gemfile.lock files first, then does `bundle install` then copies the rest of the app

**Comment by shageman** [comment]
In trying to wrap my head around how to solve for this, I have another question.

Would this problem go away if you vendored all of your dependencies? I.e., follow http://ryan.mcgeary.org/2011/02/09/vendor-everything-still-applies/ I believe this to be a prudent strategy for any production deploy as it removes availability issues and creates consistency between deploys.

**Comment by MadBomber** [comment]
Its been about six years since you started down this CBRA path and a few years since your book.  Are you still okay with having lots of source code for private un-built engines and gems in your main appolication's repository?

**Comment by shageman** [comment]
Hi @MadBomber!

The short answer is *yes*.

In the six years you mention I have seen several teams adopt this approach and make it work (some have pulled back from it, some didn't). I still believe that the pain of maintaining the code necessary to maintain components is much less than the pain of a hard-to-manage ball of mud.

I assume that you are talking about the code within `spec/dummy`... that's the only place where I have felt some pain and it basically only comes into play when upgrading Rails versions. I have found this issue to be very manageable.
